import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import { HMSRoomProvider } from "@100mslive/react-sdk";

const Home: NextPage = () => {
  return (
    <HMSRoomProvider>
      <div>
        <Head>
          <title>Eddys Video Chat</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Login />
      </div>
    </HMSRoomProvider>
  )
}

export default Home
